ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'RECEPTIE';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'IN_LUCRU';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'IN_ASTEPTARE';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'FINALIZATA';
