import { describe, expect, it } from "vitest";

import {
  OVERRIDE_ELIGIBLE_PERMISSION_KEYS,
  PERMISSION_REGISTRY,
  PERMISSION_SCOPES,
  RBAC_ROLE_KEYS,
  ROLE_PERMISSION_MATRIX,
} from "./permission-registry.js";

const expectedPermissionKeys = [
  "users.create",
  "users.read",
  "users.update",
  "users.disable",
  "users.assign_roles",
  "roles.read",
  "permissions.read",
  "organization_context.read",
  "organization_context.switch",
  "patients.read",
  "patients.create",
  "patients.update",
  "patients.archive",
  "patients.documents.read",
  "clinics.create",
  "clinics.read",
  "clinics.update",
  "clinics.archive",
  "doctors.create",
  "doctors.read",
  "doctors.update",
  "doctors.archive",
  "works.create",
  "works.read_all",
  "works.read_assigned",
  "works.update",
  "works.urgency.update",
  "works.deadline.current.update",
  "works.assign",
  "works.change_status",
  "works.archive",
  "works.deadline.preview",
  "works.deadline.read",
  "works.deadline.recalculate",
  "works.deadline.set_manual",
  "works.deadline.override_lock",
  "works.technical_details.read",
  "works.technical_details.update",
  "works.production.finalize",
  "works.production.probe_ready",
  "works.claim.available.read",
  "works.claim.own.read",
  "works.claim.create",
  "works.claim.release_own",
  "works.claim.release_any",
  "works.claim.assign",
  "works.claim.reassign",
  "works.claim.history.read",
  "works.execution_snapshot.read",
  "works.execution_snapshot.read_pricing",
  "works.execution_snapshot.read_deadline",
  "works.execution_snapshot.history.read",
  "works.execution_snapshot.create",
  "works.item.create",
  "works.item.update",
  "works.item.remove",
  "works.scope.update",
  "works.connections.manage",
  "works.custom_type.use",
  "works.custom_platform.use",
  "works.custom_type.save_to_catalog",
  "works.custom_platform.save_to_catalog",
  "cycles.read",
  "cycles.history.read",
  "cycles.create_next",
  "cycles.probe_type.select",
  "cycles.mark_received",
  "probe_types.read",
  "probe_types.manage",
  "scan.use",
  "scan.resolve",
  "workflow.read",
  "workflow.configure",
  "workflow.create",
  "workflow.update",
  "workflow.archive",
  "workflow.assign_stage",
  "workflow.start_stage",
  "workflow.pause_stage",
  "workflow.complete_stage",
  "workflow.reassign_stage",
  "workflow.reopen_stage",
  "technician.workbench.read",
  "technician.workload.read",
  "technician.operations.read",
  "technician.operations.manage_own",
  "technician.operations.scope.select",
  "technician.operations.configure",
  "technician.rates.read",
  "technician.rates.manage",
  "technician.earnings.read_own",
    "technician.earnings.read_all",
    "technician.payments.create",
    "technician.payments.read_all",
  "technician.payments.read_own",
  "notifications.read_own",
  "notifications.mark_read_own",
  "notifications.dismiss_own",
  "logistics.read",
  "logistics.plan",
  "logistics.assign",
  "logistics.prepare_delivery",
  "logistics.center.read",
  "logistics.update_location",
  "logistics.block_work",
  "logistics.unblock_work",
  "logistics.prepare_work",
  "logistics.manage_groups",
  "logistics.alerts.update",
  "logistics.delivery_marker.update",
  "pickup.create",
  "pickup.read",
  "pickup.update",
  "pickup.cancel",
  "routes.create",
  "routes.read",
  "routes.assign",
  "routes.update",
  "routes.cancel",
  "routes.execute_own",
  "routes.correct_outcome",
  "reception.receive",
  "reception.edit_intake",
  "reception.handover_to_logistics",
  "reception.handover_to_courier",
  "delivery.read_own",
  "delivery.read",
  "delivery.create",
  "delivery.assign",
  "delivery.create_route",
  "delivery.pickup",
  "delivery.start_transit",
  "delivery.complete",
  "delivery.deliver",
  "delivery.fail",
  "delivery.reschedule",
  "delivery.cancel",
  "delivery.capture_signature",
  "delivery.signature.capture",
  "delivery.signature.read",
  "delivery.signature.override",
  "delivery.proof.print",
  "quality.read",
  "quality.approve",
  "quality.reject",
  "quality.rework",
  "finance.read",
  "finance.record_payment",
  "finance.refund",
  "finance.read_reports",
  "invoice.create",
  "invoice.read",
  "invoice.download",
  "invoice.cancel",
  "invoice.configure_series",
  "invoice.storno.create",
  "invoice.storno.read",
  "discounts.read",
  "discounts.manage",
  "pricing.read",
  "pricing.create",
  "pricing.update",
  "pricing.archive",
  "pricing.resolve_preview",
  "pricing.agreements.read",
  "pricing.agreements.manage",
  "forms.read",
  "forms.create",
  "forms.update",
  "forms.archive",
  "work_forms.real.read",
  "work_forms.real.update",
  "work_forms.real.finalize",
  "work_forms.real.history.read",
  "work_forms.real.manage_templates",
  "reports.operational",
  "reports.financial",
  "reports.productivity",
  "settings.read",
  "settings.update",
  "audit.read",
  "files.upload",
  "files.read",
  "files.delete",
  "comments.create",
  "comments.read_internal",
  "comments.read_external",
] as const;

describe("PERMISSION_REGISTRY", () => {
  it("contains every MVP matrix permission exactly once", () => {
    const keys = PERMISSION_REGISTRY.map((permission) => permission.key);

    expect(keys).toHaveLength(expectedPermissionKeys.length);
    expect(new Set(keys).size).toBe(keys.length);
    expect([...keys].sort()).toStrictEqual([...expectedPermissionKeys].sort());
  });

  it("defines resource, action, description, and valid allowed scopes", () => {
    for (const permission of PERMISSION_REGISTRY) {
      expect(permission.resource).toBeTruthy();
      expect(permission.action).toBeTruthy();
      expect(permission.description).toBeTruthy();
      expect(permission.allowedScopes.every((scope) => PERMISSION_SCOPES.includes(scope))).toBe(true);
    }
  });

  it("maps all seeded role grants to valid permission scopes", () => {
    for (const roleKey of RBAC_ROLE_KEYS) {
      const matrix = ROLE_PERMISSION_MATRIX[roleKey];

      for (const permission of PERMISSION_REGISTRY) {
        const grant = matrix[permission.key];

        expect(grant === null || PERMISSION_SCOPES.includes(grant)).toBe(true);
      }
    }
  });

  it("does not grant override-only permissions implicitly for selected matrix O cells", () => {
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["invoice.create"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["finance.read"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.urgency.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.CURIER["works.urgency.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MEDIC["works.urgency.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MEDIC["audit.read"]).toBeNull();
    expect(OVERRIDE_ELIGIBLE_PERMISSION_KEYS).toContain("works.update");
  });

  it("keeps representative matrix permissions with expected scopes", () => {
    expect(ROLE_PERMISSION_MATRIX.MANAGER["users.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["works.read_all"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["works.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["works.urgency.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["works.deadline.current.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["clinics.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["doctors.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["workflow.complete_stage"]).toBe("OWN_STAGE");
    expect(ROLE_PERMISSION_MATRIX.CURIER["delivery.complete"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.CURIER["delivery.start_transit"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["clinics.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.urgency.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.deadline.current.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["doctors.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["cycles.create_next"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["cycles.create_next"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["cycles.history.read"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.CURIER["cycles.read"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.MEDIC["cycles.create_next"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["clinics.create"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["doctors.create"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MANAGER["pricing.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["pricing.read"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["pricing.read"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MANAGER["forms.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["forms.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["forms.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["work_forms.real.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["work_forms.real.update"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["work_forms.real.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["work_forms.real.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MEDIC["work_forms.real.update"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["forms.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["forms.archive"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.workbench.read"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.operations.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.operations.manage_own"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.earnings.read_own"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.earnings.read_all"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.rates.manage"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.claim.available.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.claim.create"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.claim.release_own"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.claim.release_any"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.technical_details.update"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.production.finalize"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.production.probe_ready"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.operations.scope.select"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["technician.operations.configure"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.custom_type.save_to_catalog"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["works.custom_platform.save_to_catalog"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["logistics.alerts.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["logistics.delivery_marker.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["pickup.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["routes.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["routes.correct_outcome"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.CURIER["routes.read"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.CURIER["routes.execute_own"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.CURIER["pickup.read"]).toBe("OWN_DELIVERY");
    expect(ROLE_PERMISSION_MATRIX.CURIER["routes.create"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MANAGER["works.claim.reassign"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["technician.rates.manage"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["technician.earnings.read_all"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["discounts.manage"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["invoice.storno.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["scan.use"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["scan.resolve"]).toBe("ASSIGNED");
    expect(ROLE_PERMISSION_MATRIX.MEDIC["scan.use"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MANAGER["technician.workload.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["workflow.assign_stage"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MEDIC["audit.read"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.MANAGER["audit.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["organization_context.read"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.MANAGER["organization_context.switch"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["organization_context.switch"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.TEHNICIAN["organization_context.switch"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["organization_context.switch"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.CURIER["organization_context.switch"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.item.create"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.scope.update"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.connections.manage"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["cycles.probe_type.select"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["cycles.mark_received"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.custom_type.save_to_catalog"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.RECEPTIE["works.custom_platform.save_to_catalog"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["works.connections.manage"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.CURIER["works.item.create"]).toBeNull();
    expect(ROLE_PERMISSION_MATRIX.CURIER["notifications.read_own"]).toBe("ALL");
    expect(ROLE_PERMISSION_MATRIX.LOGISTICA["notifications.read_own"]).toBe("ALL");
  });
});
