-- B13 was realigned before deployment. Technician maneuver rates are globally
-- interpreted as currency per explicitly selected adult FDI element, so this
-- migration intentionally makes no schema change.
